### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by lornajane**
I think the docker-compose setup is pretty much ready to go, please check and merge if appropriate

### CODE REVIEW

**Comment by lornajane** [comment]
I'm not sure if I should also have undone the db config changes we made earlier. This thought brought to you by Friday afternoon, if I don't write this down I will not remember!

**Comment by lornajane** [comment]
@lukeocodes Here's the demo I think is most useful for LaraCon EU. Can you please try this branch and (after you've fixed stuff) merge it in? This adds the docker support and some other fixes.

**Comment by lornajane** [comment]
Hey @lukeocodes can you update this PR with how you are getting on? @kellyjandrews is going to lend us a hand to iron out the issues but he needs a bit more info on what happens when you try it.

Also note that I think you need a _fresh clone_ - weird things will happen if you've already run the project locally in the same directory

**Comment by kellyjandrews** [comment]
@lornajane Slight confusion on the `private.key` location. 

In `.env` it's listed as `NEXMO_PRIVATE_KEY=./private.key`

In the `.gitignore` it has a line for `/storage/*.key`

I can add `./private.key` to `.gitignore` or I can modify `.env` to`NEXMO_PRIVATE_KEY=./storage/private.key` and update the app generation line.  

Which would we prefer?

**Comment by kellyjandrews** [comment]
Ok - `docker-compose up` works. I'm going to take a peek at removing the key generation and migration steps to make that happen automatically on start up. 

Otherwise not knowing how the app works, I was able to register and login no problem. Also pushing up a fix to a case-insensitivity issue.

**Comment by kellyjandrews** [comment]
I went ahead and just added `private.key` to the `.gitignore` file - seemed to be the most pragmatic.

**Comment by mheap** [comment]
We can’t make key generation happen on startup as it will rotate the
encryption key, breaking all hashed data

**Comment by kellyjandrews** [comment]
@mheap Right - Some of the stuff can happen in a one time only script that would make it less work in setting up.  If I don't have anything super useful, it should be fine as is.

**Comment by lornajane** [comment]
Spot on @kellyjandrews I think those are two different private keys - one for Laravel in the storage folder and one for the Nexmo voice application in the root directory.

Over to @lukeocodes to try this version and share any errors that he's still seeing I think

**Comment by lukeocodes** [comment]
So when I try to migrate, I get the following error.

```
16:53 $ docker-compose exec web php artisan migrate

In Connection.php line 664:
                                                                                                                                                    
  could not find driver (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations and table_type =   
  'BASE TABLE')                                                                                                                                     
                                                                                                                                                    

In Connector.php line 70:
                         
  could not find driver  
                         
```

**Comment by mheap** [comment]
Did you copy .env.example or .env.docker?

**Comment by lukeocodes** [comment]
That was it. I had it right, then edited .env, then recloned after the updates, then failed to restore the right .env file.

**Review by lukeocodes — APPROVED** [review]
Works great for me locally and with Docker. Really great. Thanks!

**Comment by lornajane** [comment]
Thanks everyone!

**Pull request merged**
